name: id1_client
description: client for id1 api
version: 1.0.0
repository: https://github.com/qodex/id1-client-dart

environment:
  sdk: ^3.7.3

dependencies:
  logging: ^1.3.0
  http: ^1.4.0
  uuid: ^4.5.1
  pointycastle: ^4.0.0
  asn1lib: ^1.6.4
  dart_jsonwebtoken: ^3.2.0
  websocket_universal: ^1.2.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
